In [1]:
import numpy as np 

# Numerical Python. 

In [20]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr[0]))

[1 2 3 4 5]
<class 'numpy.int32'>


In [26]:
print(arr.shape) # tamaño de 5, esto quiere decir que es un array unidimensional 

(5,)


In [30]:
print(arr[1])
print(type(arr[1]))

2
<class 'numpy.int32'>


In [31]:
x_1 = arr.reshape(5,1) # 5 filas una columna 
print(x_1)
print((x_1[1]))
print(type(x_1[1]))

[[1]
 [2]
 [3]
 [4]
 [5]]
[2]
<class 'numpy.ndarray'>


In [38]:
print(x_1.T.shape)
print(x_1.T)
print(type(x_1.T))

(1, 5)
[[1 2 3 4 5]]
<class 'numpy.ndarray'>


In [39]:
x_2 = arr.T
print(x_2)
print((x_2[1]))
print(type(x_2[1]))
print(x_2.shape)

[1 2 3 4 5]
2
<class 'numpy.int32'>
(5,)


In [41]:
arr_2 = np.array((1, 2, 3, 4, 5))
print(arr_2)

[1 2 3 4 5]


 # TIPOS DE NUMPY ARRAYS 

## Los números son array 0 dimensionales 

In [48]:
numero = np.array(12)
print(type(numero))
print(numero.size)
print(numero.shape)

<class 'numpy.ndarray'>
1
()


## Un vector de tipo 'fila' es un array unidimensional 1-D 

In [75]:
vector = np.array([1, 2, 3, 4, 5])
print(type(vector))
print(vector.size)
print(vector.shape)
print(vector.dtype) # mirar los tipos de archivos que se encuentran dentro del array. 

<class 'numpy.ndarray'>
5
(5,)
int32


## Matrices o tensores de 2do orden son arrays de 2-D

In [61]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
print(type(matriz))
print(matriz.size)
print(matriz.shape) # 2 filas y 3  columnas 
print(matriz[0,2]) # primera fila (0) , tercera columna (2)
print(matriz[0][2]) # también se puede llamar de esta forma 

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
6
(2, 3)
3
3


In [58]:
matriz.ndim # la matriz tiene solo 2 dimensiones 

2

## Matrices de 3 dimensiones o tensores de 3er orden 


In [68]:
matriz_tri_dimensional = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(matriz_tri_dimensional)
print(type(matriz_tri_dimensional))
print(matriz_tri_dimensional.size) # 12 elementos en total 
print(matriz_tri_dimensional.shape) #  2 canales cada uno con 2 filas y  3 columnas 
print(matriz_tri_dimensional[1,:,:]) # el segundo canal 
print(matriz_tri_dimensional[:,0,:]) # las primeras filas de ambos canales.


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
12
(2, 2, 3)
[[ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [7 8 9]]


In [57]:
matriz_tri_dimensional.ndim # dice que la matriz tri dimensional tiene tres dimensiones 

3

In [60]:
arr_multidimensional = np.array([[1, 2, 3], [4, 5, 6]], ndmin=5) # con este argumento le puedo pasar el número de dimensiones 

print(arr_multidimensional)
print('number of dimensions :', arr_multidimensional.ndim)

[[[[[1 2 3]
    [4 5 6]]]]]
number of dimensions : 5


In [70]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('2nd element on 1st dim: ', arr[0, 1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st dim:  2


## Slice de los arrays 

In [71]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [73]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


## Desde la posición 1 (número 2) hasta la posición 5 (número 6) de a pasos de a 2. No se toma el último número  

In [72]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2]) 

[2 4]


In [74]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [78]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(type(arr[0]))
print(arr.dtype)

[b'1' b'2' b'3' b'4']
<class 'numpy.bytes_'>
|S1


In [ ]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

In [79]:
# con copy hacemos una copia del array , lo que hagamos en el array copia no afecta al array original y viceversa 
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [80]:
# Con la función de view los cambios que se hagan al original también afectan a la copia y viceversa 
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [81]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


# Reshape 

In [83]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)
print(arr)
print(arr.shape)
print(newarr)
print(newarr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


## Pasamos de un arreglo unidimensional a uno tridimensional, las dimensiones deben coincidir con el número de elementos del array original. 

## No se sabe todas las dimensiones a las cuales queremos llevar el reshape por lo tanto pasamos un -1 y numpy lo calcula por nosotros 

In [84]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Aplastar el array pasarlo de cualquier n-dimension a un array unidimensional. 

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

In [85]:
# si iteramos en un array de 2 dimensiones lo hacemos por default en sus filas. 
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [103]:
# Para recorrer a lo largo de las columnas 
columns = arr.shape[1]
print(columns)
x = range(columns)
print(x)
for i in x:
    print(arr[:,i])

3
range(0, 3)
[1 4]
[2 5]
[3 6]


In [104]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr.T:
  print(x)

[1 4]
[2 5]
[3 6]


In [86]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [105]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


## Iteramos con el correspondiente indice del valor en el que estamos 

In [106]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [107]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## Concatenar dos arrays 

In [108]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [110]:
# Concatenamos a lo largo de columnas (UNO AL LADO DEL OTRO)

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr1)
print(arr2)
print(arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [115]:
# Concatenamos a lo largo de las filas (UNO ENCIMA DEL OTRO)
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [133]:
# Uno encima del otro como filas 
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [134]:
# Uno al lado del otro como columnas 
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)
print(arr.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


##  H stack para concatenar uno seguido del otro en forma de fila 

In [135]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)
print(arr.shape)

[1 2 3 4 5 6]
(6,)


## V stack es a lo largo de las columnas 

In [128]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## D stack es a lo largo de height que es igual que el depth 

In [132]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)
print(arr.shape)

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


In [136]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [137]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [4]:
# así dividimos por filas 

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)
print(arr)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [6]:
# así dividimos por columnas 
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(arr)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


##  Buscar dentro de un array 

In [7]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [9]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [10]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


['apple' 'banana' 'cherry']


In [11]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


## Random 



In [13]:
# un entero aleatorio entre 0 y 100 
x = np.random.randint(100)
print(x)

14


In [14]:
# número de punto flotante random entre 0 y 1 
x = np.random.rand()

print(x)

0.33985694084521767


In [18]:
x=np.random.randint(100, size=(5))

print(x)

[88  9 97 63 47]


In [26]:
x = np.random.choice([3, 5, 7, 9])
print(x)

7


In [28]:
# media 1 y desviación estándar de 2  
x = np.random.normal(loc=1, scale=2, size=(2, 3))

print(x)

[[ 1.37069525 -1.36007224 -1.88191813]
 [ 0.88875624  4.154245    2.03324884]]


### [Keith Galli tutorial](https://www.youtube.com/watch?v=GB9ByFAIAH4&list=PLFCB5Dp81iNVmuoGIqcT5oF4K-7kTI5vp&index=10&ab_channel=KeithGalli)



In [1]:
import numpy as np
import sys

#### one dimensional array 

In [3]:
# 3 x 4 matrix : 3 rows 4 columns. 

a = np.array([1,2,3])
a

array([1, 2, 3])

#### two dimensional array 

In [10]:
b = np.array([[2,4,6,8],[1,3,5,7]])
b

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

#### Get the dimensions of a numpy array 
## Function array.ndim 

In [9]:
print("a has {} dimensions".format(a.ndim))
print("b has {} dimensions".format(b.ndim))

a has 1 dimensions
b has 2 dimensions


#### Get the number of elements in a array 

## Function np.size(array)

In [4]:
np.size(a)

3

In [11]:
np.size(b) 

8

#### Get the shape of an array 

## Function array.shape

In [12]:
print(a.shape)
print(b.shape)

(3,)
(2, 4)


#### Get the type of the array 

## Function array.dtype

In [13]:
print(a.dtype)
print(b.dtype)

int32
int32


#### Casting the dtype

In [14]:
a = np.array([1,2,3], dtype= 'int16')

In [15]:
a.dtype

dtype('int16')

## Accesing/ changing specific elements, rows, columns etc 

In [16]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [18]:
c.ndim

2

In [19]:
c.shape

(2, 7)

#### Get a specific element of the array 

### The notation is [row,colum]

In [22]:
c[1,5] # second row, 4 column 

13

In [23]:
c[1][5] # second row, 4 column 

13

In [24]:
c[1,-2]

13

### Get a row of the array 

In [26]:
c[0] # first row 

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
c[1] # second row

array([ 8,  9, 10, 11, 12, 13, 14])

In [29]:
c[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

### Get a column of the array 

In [30]:
c[:,2]

array([ 3, 10])

In [31]:
c[0,1:6:2] # it would be to the 5th index but, because python is exclusive we need to put one extra number. 
# start, finish (exclusive), step 
# 1       6                   2 

array([2, 4, 6])

In [33]:
c[1,5] = 20
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [35]:
c[:,2] = 5 # change the numbers in the third column with the number 5 
c

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

### Tree dimensional array 

In [37]:
tree_dimensional = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
tree_dimensional

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [38]:
tree_dimensional.ndim

3

In [39]:
tree_dimensional.shape

(2, 2, 2)

### Get an element from the array (work outside in)

In [40]:
tree_dimensional[0,1,1]

4

In [41]:
tree_dimensional[0][1][1] # the first [0] dimension or layer with repect the depth,  Second row [1], second column[1] 

4

In [43]:
tree_dimensional[:,1:,] # all the stacks with respect the depth [:], second row[1], all the columns[:] 

array([[[3, 4]],

       [[7, 8]]])

In [45]:
tree_dimensional[:,1,:] =[[9,9],[8,8]]

In [46]:
tree_dimensional

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initialize different types of arrays. 

## Functions : np.zeros, np.ones, np.full, np.full_like 

In [48]:
# All 0s array

np.zeros(5,)

array([0., 0., 0., 0., 0.])

In [52]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
np.zeros((3,8,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [54]:
np.zeros((2,3,8,7)) # 4 dimensional like a tensor

# this is a stack of 2 tree dimensional arrays each one of shape 3*8*7 

array([[[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0.,

#### np.ones

In [55]:
# All 1s matrix 

In [56]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

#### Initializing a matrix with different numbers. 

## Function : np.full(shape,number to fill with)

In [57]:
np.full((3,2,3),10)

array([[[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]]])

In [61]:
np.full_like(c,4) # filling with an already created array. 

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [62]:
np.full(c.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

#### Random decimal initialization numbers. 

## Functions:
* np.random.rand(dimensions) **without being a tuple**
* np.random.rand_sample(dimensions) **tuple**

In [65]:
np.random.rand(5,2) 

array([[0.71256544, 0.89892446],
       [0.20190524, 0.59584702],
       [0.79004904, 0.79323686],
       [0.93193219, 0.31515434],
       [0.33871611, 0.47500839]])

In [71]:
random_init = np.random.rand(2,3,4,5)
random_init

array([[[[4.38651565e-01, 6.65544323e-01, 9.05227888e-01,
          6.46460657e-01, 9.17613728e-02],
         [8.09905610e-01, 1.63029008e-01, 5.81945339e-01,
          9.06674413e-02, 4.57286228e-01],
         [1.53454933e-01, 2.98258159e-01, 3.56066557e-01,
          6.06020338e-01, 2.58463646e-01],
         [2.64846088e-01, 5.16670230e-01, 1.14013445e-01,
          9.30774928e-01, 1.32561264e-01]],

        [[9.13993235e-01, 2.91716489e-01, 2.26569567e-01,
          6.23610362e-01, 8.22780495e-01],
         [9.83868916e-01, 7.02830552e-01, 2.78112502e-01,
          5.69509256e-01, 5.10061446e-01],
         [6.90633709e-03, 4.15563118e-01, 1.44670321e-01,
          8.11508977e-01, 4.72244654e-01],
         [9.15557602e-01, 2.08565096e-01, 8.01363265e-01,
          1.61640313e-01, 5.54055772e-02]],

        [[2.06165475e-01, 7.03881627e-01, 3.10026001e-01,
          2.80647771e-01, 7.27993174e-01],
         [4.31174567e-01, 7.29109181e-01, 8.71352366e-01,
          4.74505721e-02, 5.2

In [72]:
print(random_init.shape)
print(random_init.ndim)

(2, 3, 4, 5)
4


In [74]:
random_init_2 = np.random.random_sample((3,2,2,3))
random_init_2

array([[[[0.14128189, 0.31170316, 0.64153874],
         [0.74812506, 0.12530907, 0.76152947]],

        [[0.99290451, 0.05839402, 0.3237026 ],
         [0.30702694, 0.12259298, 0.02143817]]],


       [[[0.75369882, 0.46014107, 0.40113437],
         [0.50420621, 0.15567426, 0.99457965]],

        [[0.97135082, 0.15424283, 0.44059944],
         [0.66507401, 0.14328055, 0.18457792]]],


       [[[0.11461994, 0.29080642, 0.52891752],
         [0.80094376, 0.91372415, 0.94112032]],

        [[0.24224788, 0.30794983, 0.68210234],
         [0.18260015, 0.11154455, 0.62024643]]]])

#### Random integer values. 

## Functions:

* np.random.randint(number top which is going to fill, size)

In [75]:
np.random.randint(1,6,size=(3,2,4)) # exclusive with respect the 6 

array([[[1, 2, 3, 1],
        [4, 2, 4, 5]],

       [[2, 4, 3, 3],
        [3, 2, 2, 3]],

       [[4, 1, 3, 5],
        [5, 5, 2, 4]]])

#### Identity matrix 

## Function np.identity(size)

In [76]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Repeat an array. 

In [78]:
arr = np.random.randint(1,4,size=(2,3))
arr

array([[2, 2, 1],
       [1, 1, 1]])

In [81]:
r1 = np.repeat(arr,3,axis=0) 
r1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# AXIS = 0 REPRESENT ROWS. 
# AXIS = 1 REPRESENT COLUMNS.

In [82]:
r2 = np.repeat(arr,3,axis=1)
r2

array([[2, 2, 2, 2, 2, 2, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [87]:
outer = np.ones((5,5))
inner = np.zeros((3,3))
print(outer)
print(inner)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [88]:
outer[1:4,1:4] = inner
print(outer)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [89]:
outer[2,2] = 9

In [90]:
outer

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Copying arrays. 

In [91]:
a = np.array([1,2,3])
b = a.copy()
b [0] = 100 
print(a)
print(b)

[1 2 3]
[100   2   3]


# MATH OPERATIONS. 

### Element wise (ONE VS ONE) operations. 

In [94]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [95]:
a+2 # sum 2 to all the elements of an array. 

array([3, 4, 5, 6])

In [96]:
a*2

array([2, 4, 6, 8])

In [97]:
a **2

array([ 1,  4,  9, 16], dtype=int32)

In [99]:
np.exp(2) # e**2 

7.38905609893065

In [100]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### Linear Algebra. 

In [104]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [108]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [107]:
np.dot(a,b)

array([[6., 6.],
       [6., 6.]])

In [109]:
# Determinant 
c = np.identity(3)
np.linalg.det(c)

1.0

### Math and linear algebra numpy references. 

In [ ]:
# https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
# https://docs.scipy.org/doc/numpy/reference/routines.math.html

In [121]:
stats = np.array([[1,8,3],[4,5,6]])
stats

array([[1, 8, 3],
       [4, 5, 6]])

In [122]:
np.min(stats)

1

In [123]:
np.min(stats, axis=0) # min value of each column 

array([1, 5, 3])

In [125]:
np.min(stats, axis = 1) # min value of each row 

array([1, 4])

In [126]:
np.max(stats)

8

In [127]:
np.argmax(stats) # indices of the maximum element. 

1

In [128]:
np.argmax(stats, axis = 1) # along the column axes 

array([1, 2], dtype=int64)

In [129]:
np.sum(stats)

27

In [131]:
print(stats)
print(np.sum(stats, axis = 0)) # along the columns 

[[1 8 3]
 [4 5 6]]
[ 5 13  9]


In [132]:
print(stats)
print(np.sum(stats, axis = 1)) # along the rows 

[[1 8 3]
 [4 5 6]]
[12 15]


## Reorganizing arrays. 

In [148]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

after_1 = before.reshape((8,))
print(after_1)
print(after_1.shape)

after_2 = before.reshape((8,1))
print(after_2)
print(after_2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[1 2 3 4 5 6 7 8]
(8,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(8, 1)


#### vertical stack (vstack) must have the same number of rows.

In [135]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

#### horizontal stack (hstack) must have the same number of rows. 

In [136]:
# Horizontal  stack 
h1 = np.ones((2,4))
print(h1)
h2 = np.zeros((2,2))
print(h2)

np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [144]:
a = np.ndarray((2,4))
a
type(a)

numpy.ndarray

In [150]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [154]:
np.any(before > 4,axis = 1) # in the first row there are not values greater than 4 but in the second one they are. 

array([False,  True])

In [156]:
np.any(before > 4,axis = 0) # with respect the columns there are at least one value that is greater than 4 

array([ True,  True,  True,  True])

In [158]:
np.all(before > 4,axis = 1) # with respect the rows only all the values of the second row are greater than 4.  

array([False,  True])

In [157]:
np.all(before > 4,axis = 0) # when using np.all all the values in that axes must be greater than the given value 

array([False, False, False, False])

In [159]:
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [161]:
before[[0,1],[1,2]] # accesing the first and second row and the second and third element respectively. 

array([2, 7])

## Creating a range of number from start to end exclusive 

In [3]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = np.arange(0,10,step = 2)
arr

array([0, 2, 4, 6, 8])

In [9]:
arr = np.linspace(0,10,10)
arr

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])